# -*- coding: utf-8 -*-
"""Prompt to image Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixZ1jdzt743Ou8AlTT1JogxyA2LyQJRk

Install the dependencies and import the packages.
"""

!pip install gradio
from diffusers import StableDiffusionPipeline
import torch
import gradio as gr

"""Load the Stable Diffusion pipeline"""

model_id = "stabilityai/stable-diffusion-2-1"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.enable_attention_slicing()

"""Define the image generation function"""

def generate_image(prompt):
    image = pipe(prompt, guidance_scale=9.0, num_inference_steps=60).images[0]
    image.save("output_image.png")
    return image

"""Create the Gradio interface"""

interface = gr.Interface(
    fn=generate_image,
    inputs=gr.Textbox(label="Enter your prompt"),
    outputs=gr.Image(label="Generated Image"),
    title="Stable Diffusion Image Generator",
    description="Enter a prompt to generate an image using Stable Diffusion"
)

""" Launch the UI for multiple users"""

interface.queue().launch(share=True)